#!/usr/bin/env bash
# shellcheck disable=SC2154
# @describe Command utilities.
# @author Guzmán Monné
# @version 0.1.0

# @cmd Runs a project app
# @option -b --bin=a Binary to execute
run() {
  cargo run --bin "$argc_bin" -- "${argc__args[@]}"
}

eval "$(argc "$0" "$@")"
