#!/usr/bin/env bash
# shellcheck disable=SC2154
# @describe Commands to build v2 version of the app
# @author Guzmán Monné
# @version 0.1.0

ROOT="$(git rev-parse --show-toplevel)"

utils="$ROOT/scripts/utils"
bin="v2"

# @cmd Runs the v2 version of the app
run() {
  $utils run --bin "$bin" -- "${argc__args[@]}"
}

eval "$(argc "$0" "$@")"
